[workspace]
members = ["programs/protocol"]

[build]
use_docker = false

[programs.localnet]
protocol = "7Huo5pfufAtTyPufiZ9XZGcRLHZyPcnbsjyCDYk8G8iB"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn test"




[test.validator]
bind_address = "127.0.0.1"

